const { Module } = require('../main');

const shayaris = [
    "HATE ME I DONT CARE",
    "LEAVE ME I DONT CARE",
    "EK TU H TU H RHYGII",
    "TERE BIN MAR JAUNGA",
    "TU MERI H SMJI?",
    "KOI TERE MERE BEECH AYA MARDUNGA OSE",
    "TERE LIYE MAR B SKTA HU MAR B SKTA HU",
    "TERE SE JITNA MRJI GUSSA HO JAUN BUT I LOVE U YARR",
    "TERE LIE IS DUNIA SE LAD JAUNGA",
    "ANKO SE ANKHE MILAKE KHWAB CHURA LU TERE",
    "TERA ISHQ PANE LIE KITNE BETAN HU KESE BATAU TUJE",
    "ME JO JEE RHA HU WAJH TUM HO",
    "TU H TO M HU TUJSE M HU",
    "TUJE KITNA CHAHNE LAGE HAM KI SHBO M BYAN NA KAR PAYNGE",
    "CURRENT STATUS  I WANT TO HUG YOU AND WANAA CARRY LOUD",
    "I NEED YOU IN MY BAD IN MY GOOD",
    "HMESHA TERE SATH HU",
    "TERE SE KADM SE KDM MILAKE CHALNA CHHTA HU",
    "TUJE APNI SHOTI SI DUNIA KA EK BHT BADA HISA BANANA CHAHTA HU",
    "KYA JANE TU MERE IRADHE LE JAUNGA TERI SANSE CHURAKE",
    "DIL KHE RHA KI GUNHGAGAR BAN JA BADA SKOON H IN GUNAHO M",
    "MERI KHUSHNMA SUBH H TU",
    "MERI JAAN H TU",
    "EVEN TUJE IDEA B NHI H KI TERE EK SINGLE MESSAGE KA WAIT KRTE KRTE KITAN ROYA HU",
    "TUJE PANE LIE BHT TDFA HU",
    "KABI KABI LGTA H KI TUN MUJSE NHT DUR JA RHI H",
    "I DONT CARE ABOUT WORD BS I NEED YOU",
    "TUN BAS MERI H MERI RHNA",
    "BHT ROTA HU TERE LIE AKELA ME",
    "H YE NSHA YAN H JEHAR IS PYAR KO KYA NAM DU",
    "HMARE PYAR KI H YE ADHURI DASTA KI TUN PASS HOKE B BHT DOOR H",
    "PLZZ KABI MAT SHODNA MUJE I CANT LIVE WITHOUT YOU",
    "DO JISM H BUT EK JAAN H HAM DO",
    "MUJE BAS TU CHHIE NAHI PTA KYU BUT CHHIE TU H",
    "THERE ARE MANY PEOPLE IN WORLD BUT I ONLY NEED YOU",
    "WO TERA GUSSA HONA JHGDE KRNE I MISS YOU",
    "BHT PYAR KRTA HU TERE SE PLZZ DONT LEAVE ME",
    "Tere naalo challiye haseen koyi NA 😁😁",
    "Taare chann ambar zameen koyi nA",
    "Main Jado Tere Mode Utte Sir Rakheya🧐🧐",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😖😖",
    "Sohniyan Vi Laggan Giyan Fer Walian😍😍",
    "Galan Nal Jado Takraiyan Waliyan🥰🥰",
    "Tare Dekhi Labh Labh Kiven Harde😁😁",
    "Tu Bala Ch Lakoiyan Jado Ratan Kaliyan😒😒",
    "Main Sab Kuj Har Tere Utton De’unga😌😌",
    "Sab Kuj War Tere Utton De’unga😉😉",
    "Akhir Ch Jan Tainu De’un Apni😎😎",
    "Chala Tainu Bhavein Pehli War De’unga😚😚",
    "Han Main Cheti Cheti Lawan😫😫",
    "Tere Nal Laini an😣😣",
    "Samay Da Tan Bhora Vi Yakeen Koi Na🥺🥺",
    "Tere Nalo Jhaliye Haseen Koi Na🥰🥰",
    "Tare Chann Ambar Zameen Koi Na😘😘",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Tu Yar Mera Tu Hi Ae Sahara AdiyE",
    "Main Pani Tera Mera Tu Kinara Adiye",
    "Phul Ban Jai Main Khushboo Bann Ju",
    "Deevan Bani Mera Teri Lau Ban Ju",
    "Haye Ujadiyan Thawan Te Banate Bag Ne",
    "Teriyan Ankhan Ne Kitte Jadu Yad Ne",
    "Jado Wang Kolon Phadi Vi Ni KassKe",
    "Totte Sambh Rakhe Tutte Hoye Kach De",
    "Han Ki Dil Yadan Rakhda Ae, Sambh Sambh Ke",
    "Hor Dil Sajjna Machine Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Main Jado Tere Mode Utte Sir Rakheya",
    "Eh Ton Sachi Sama Vi Haseen Koi Na",
    "Kine Din Hogye Meri Akh Soi Na",
    "Tere Ton Bagair Mera Aithe Koi Na",
    "Tu Bhukh Vi Ae Tu Hi Ae Guzara Adiye",
    "Mannu Sab Kari Tu Ishara Adiye",
    "Ho Khaure Kinni War Seene Vich Khubiyan",
    "Surme De Vich Dovein Ankhan Dubbiyan",
    "Kini Sohni Lagge Jadon Chup Kar Je",
    "Jandi Jandi Shaman Nu Vi Dhup Kar Je",
    "Haye Main Paun Farmaishi Rang Tere Sohniye",
    "Unj Bahotan Gifty Shaukeen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Kanna Wich Jhumka👀👀",
    "Akhan Wich Surma🙈🙈",
    "Ho Jaise Strawberry Candy😋😋",
    "Nakk Utte Koka🤨🤨",
    "Jeena Kare Aukha🤭🤭",
    "Haye Meri Jaan Kadd Laindi😌😌",
    "Tere Nakhre Haye Tauba Sanu Maarde🤫🤫",
    "Ho Gaya Hai Mera Baby Bura HaaL😊😊",
    "Sachi Lut Gaye Hum Tere Is Pyar Mein😏😏",
    "Jeeni Zindagi Hai Bas Tere Naal😚😚",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "Sapno Mein Mere AayI😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Sapno Mein Mere Aayi😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Tainu Diamond Mundri Pehnawa😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "Chhoti-Chhoti Gallan Utte Main Hasavaan💙💙",
    "Yaara Kade Vi Na Tainu Main Rulawaan🙊🙊",
    "cause I Love You  🙈🙈",
    "I Love You ❤️❤️",
    "cause I Love You🙈🙈",
    "I Love You ❤️❤️",
    "Yaari Laawan Sachi YaarI💫💫",
    "Tu Jaan Ton Vi Pyari😁😁",
    "Will Love You To The Moon And Back😆😆",
    "Hogi Saza Na Koyi Hogi😙😙",
    "Chahe Karun Chori Chaand Taare😉😉",
    "Imma Give You Them😅😅",
    "Yaari Laavan Sachi YaarI😘😘",
    "Tu Jaan Ton Vi PyarI😆😆",
    "Will Love You To The Moon And Back💕💕",
    "Hogee Sazaa Na Koyi Hogi💓💓",
    "Chahe Karun Chori Chaand Taare🥺🥺",
    "Imma Give You Them🥵🥵",
    "Puri Karunga Main Teri Sari Khahishein😁😁",
    "Tera Rakhanga Main Rajj Ke Khayal😘😘",
    "Kitni Khoobiyan Hai Tere Is Yaar Mein🥰🥰",
    "Aaja Bahon Mein Tu Bahein Bas Daal😂😂",
    "Aur Hota Nahi Ab Intezar🤩🤩",
    "Aur Hota Nahee Ab Intezaar😘😘",
    "cause I Love You 😍😍",
    "I Love YoU 😙😙",
    "cause I Love You",
    "I Love YoU SOOOOOOOOOOOOOOOOOO MUCHHHHHHHHHHHHHHHHHHHHH 😘😘",
    "WILL U BE MINE FOREVER??🤔🤔",
    "Je tu akh te main aan kaajal ve😌😌",
    "Tu baarish te main baadal ve🤫🤫",
    "Tu deewana main aan paagal ve🤪🤪",
    "Sohneya sohneya☺️☺️",
    "Je tu chann te main aan taara ve🤗🤗",
    "Main lehar te tu kinara ve😶😶",
    "Main aadha te tu saara ve🤗🤗",
    "Sohneya sohneya😗😗",
    "Tu jahan hai main wahan😘😘",
    "Tere bin main hoon hi kya🥲🥲",
    "Tere bin chehre se mere🤔🤔",
    "Udd jaaye rang ve😅😅",
    "Tujhko paane ke liye huM😁😁",
    "Roz mangein mannat ve🙈🙈",
    "Duniya to kya cheez hai yaara🙉🙉",
    "Thukra denge jannat ve😌😌",
    "Tujhko paane ke liye hum😌😌",
    "Roz mangein mannat ve🤫🤫",
    "Duniya to kya cheez hai yaara🤔🤔",
    "Thukra denge jannat ve😌😌",
    "Na parwah mainu apni aa😁😁",
    "Na parwah mainu duniya di👅👅",
    "Na parwah mainu apni aa😅😅",
    "Na parwah mainu duniya di👅👅",
];

Module({
  pattern: "shayari ?(.*)",
  fromMe: false,
  desc: "Spam love/sad shayari in chat",
  type: "fun"
}, async (message, match) => {
  const count = parseInt(match[1]) || 25;
  if (count > 100) return await message.sendMessage("❌ Limit: Max 100 shayaris only.");

  for (let i = 0; i < count; i++) {
    const line = shayariList[Math.floor(Math.random() * shayariList.length)];
    await message.sendMessage(line);
  }
});
