const { Module } = require('../main');

// Gali/raid list
const galiList = [
  "Sab batain bhul jha Mari pakad ke jhull jha🤣",
  "TERI MAA KI CHUT ME GHUTKA KHAAKE THOOK DUNGA 🤣",
  "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
  "TERI VAHEEN NHI HAI KYA? 9 MAHINE RUK SAGI VAHEEN DETA HU 🤣",
  "TERE PURE KHANDAN KI AURATO KO RANDI BANA DUNGA 🔥",
  "TERI MAA KO RANDI KHANE ME BECH DUNGA 💰",
  "उदास क्यों रहते हो तन्हा शाम की तरह आओ मेरा land चूसो देसी आम की तरह",
  "TERI BEHEN KA BHOSDA FAAD KE RAKJ DUNGA 🗡️",
  "TERI MAA KE BHOSDE ME HATHI KA LUND 🐘",
  "TERI BEHEN KI CHUT ME ZEHER LAGA DUNGA 🧪",
  "TERI MAA KO MERE GHAR PE NANGA NACH KARNA PADEGA 💃",
  "TERI BEHEN KI GAAND ME SARIYA DAAL DUNGA 🔨",
  "TERE PURE KHANDAN KO MERE TATTE CHATNA PADEGA 👅",
  "TERI MAA KI CHUT ME NUCLEAR BOMB 💣",
  "TERI BEHEN KE BHOSDE ME DYNAMITE 🧨",
  "TERI MAA KO JOHNNY SINS SE CHUDWA DUNGA 🎥",
  "TERI FAMILY KO MERE JUTTE CHATNE PADENGE 👞",
  "TERI MAA KA BHOSDA FAAD DUNGA 🔪",
  "TERI BEHEN KI CHUT ME ROCKET LAUNCHER 🚀",
  "TERE PURE KHANDAN KO MERE PAAS RANDI BANKE KAAM KARNA PADEGA 💼",
  "TERI MAA KO GB ROAD PE BECH DUNGA 🏪",
  "TERI BEHEN KO KOTHE PE BITHA DUNGA 🏠",
  "TERI MAA KI CHUT ME TANK GHUSA DUNGA 🚛",
  "TERE BAAP KO TERE SAMNE CHOD DUNGA 🤺",
  "TERI MAA KE BHOSDE ME HELICOPTER KA PANKHA 🚁",
  "TERI BEHEN KI CHUT ME METRO CHALWA DUNGA 🚇",
  "TERI MAA KO TERE DOSTO SE CHUDWA DUNGA 👥",
  "TERI BEHEN KI CHUT ME BANDOOK KI GOLI 🔫",
  "TERI MAA KO KUTTO SE CHUDWA DUNGA 🐕",
  "TERE PURE KHANDAN KI AURATO KO NANGI KARWA DUNGA 👯",
  "TERI BEHEN KO RANDI BAZAR ME NANGA NACHWA DUNGA 💃",
  "TERI MAA KE BHOSDE ME SUWAR KA LUND 🐷",
  "TERE BAAP KO BECH DUNGA CHAKLO PE 🏃",
  "TERI BEHEN KE BHOSDE ME CREDIT CARD 💳",
  "TERI MAA KI CHUT ME SCREW DRIVER 🔧",
  "TERE PURE KHANDAN KO MERE LUND PE NACHWA DUNGA 🕺",
  "TERI BEHEN KI CHUT ME LATHI DAAL DUNGA 🏏",
  "TERI MAA KO BISTAR PE LETA DUNGA 🛏️",
  "TERE BEHEN KE BHOSDE ME HATODA 🔨",
  "TERI MAA KI CHUT ME MURGA 🐓",
  "TERE BAAP KI GAAND ME DANDA 🎋",
  "TERI BEHEN KI CHUT ME PIPE BOMB 💣",
  "TERI MAA KO VIRAL KAR DUNGA 📱",
  "TERE PURE KHANDAN KO MERE PAAS BHIKARI BANKE AANA PADEGA 🙏",
  "TERI BEHEN KI CHUT ME LASER BEAM 🌟",
  "TERI MAA KE BHOSDE ME CYLINDER 🛢️",
  "TERE BAAP KO TERE SAMNE NACHWA DUNGA 🕴️",
  "TERI BEHEN KO WEBCAM PE NACHWA DUNGA 📸",
  "TERI MAA KI CHUT ME BULLDOZER 🚜",
  "TERE PURE KHANDAN KO MERE LUND KI DAS BANA DUNGA 👑",
  "TERI BEHEN KI GAAND ME ROCKET 🚀",
  "TERI MAA KO PORNHUB PE VIRAL KAR DUNGA 🎥",
  "TERI MAA RANDI HAI KYA BHOSDIWALE GAAND MARWA RAHA",
  "TERI MAAKA BHOSDA FAAD DIA KYA MAINE JO TAG KR RAHA RANDI KI OLAAD?",
  "ARE YAR KITNA CHODU TERI RANDI MAA KO AB TERI RANDIYO BEHEN KO BHEJ",
  "TERI MAA KI CHUT KAKTE GALI KE KUTTO ME BAAT DUNGA PHIR BREAD KI TARH KHAYENGE WO TERI MAA KI CHUT",
  "MAINE SUNA HAI TERI RANDI MAA KI CHUDAI HUI THI ROAD PAR AUR BATAU CHODNE WALA ME HI THA😂",
  "RANDI KE BACCHE TAG KYU KRA TUNE JAB TERI LADNE ME GAAND FAT TI HAI RAAND KO OLAAD TERI MAALO CHODU",
  "TERI MAA KO REDI PE BAITHAL KE USSE USKI CHUT BILWAUNGAA",
  "TERI MAAA KA LAND TERE BAAP KI CHUT TERI BEHEN DI PHUDDI FADU OYE BEHEN KE LAND",
  "JAA RE SUAR KI OLAD RANDI KA BACCHA TAG 📡",
  "MC BC BOLE TO TU 👿"
];

// Store which chats have reply raid on
const autoReplyUsers = new Set();

Module({
  pattern: 'replyraid (on|off)',
  fromMe: true,
  desc: 'Enable/disable reply gali/raid mode',
  type: 'fun'
}, async (message, match) => {
  const jid = message.jid;
  const status = match[1];

  if (status === 'on') {
    autoReplyUsers.add(jid);
    await message.sendMessage('💥 Reply Raid Mode: ON');
  } else {
    autoReplyUsers.delete(jid);
    await message.sendMessage('🛑 Reply Raid Mode: OFF');
  }
});

Module({
  on: 'message',
  fromMe: false
}, async (message) => {
  if (!message || !message.jid) return;
  if (!autoReplyUsers.has(message.jid)) return;

  const gali = galiList[Math.floor(Math.random() * galiList.length)];
  await message.sendMessage({ text: gali }, { quoted: message });
});
